%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ghisl\Documents\GitHub\GAPS-FDT_temperature_model\transfer_function_interpolation\output\all-ch_all-pts_long-fdt_module_238_-40C\all_popt_tau_4_8_params.dat
%
% Auto-generated by MATLAB on 29-Nov-2022 16:17:49

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
allpopttau48params = readtable("C:\Users\ghisl\Documents\GitHub\GAPS-FDT_temperature_model\transfer_function_interpolation\output\all-ch_all-pts_long-fdt_module_238_-40C\all_popt_tau_4_8_params.dat", opts);


%% Clear temporary variables
clear opts


%% Print means

format longG
matrix = table2array(allpopttau48params)
mean(matrix, 1)
std(matrix, 1)

histfit(matrix(:, 1), 20)